learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('learning_logs.urls'))
]

learning_logs/urls.py
"""URL patterns for learning_logs"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Topics page
    path('topics/', views.topics, name='topics'),
    #Topic entries
    path('topic/<int:topic_id>/', views.topic , name='topic')
]

learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """A topic which the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a representation of the model as a string"""
        return self.text
    
class Entry(models.Model):
    """What the user has learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Returns a representation of the model as a string"""
        if len(self.text) > 50:
            return f"""{self.text[:50]}..."""
        
        elif len(self.text) < 50:
            return self.text

learning_logs/views.py
from django.shortcuts import render
from .models import Topic

def index(request):
    """Index page for learning_logs"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Page in which all topics will be shown"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Shows the content created about a topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic, 
        'entries': entries,
        }
    return render(request, 'learning_logs/topic.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'learning_logs/base.css' %}"
</head>
<body>
    <nav>
        <ul>
            <li><a target="_blank" href="{% url 'learning_logs:index' %}">Home</a></li>
            <li><a target="_blank" href="{% url 'learning_logs:topics' %}">Topics</a></li>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<header>
    {% include 'learning_logs/navbar.html' %}
</header>
<main>
    <h1>Welcome</h1>
    <h2>My name is Daniel</h2>
    <p>
        This is kind of a blog I created to share my learning path
        in different topics.
    </p>
</main>
{% endblock %}

learning_logs/templates/learning_logs/navbar.html
<nav>
    <h1>Altin</h1>
    <ul>
        <li><a href="{% url 'learning_logs:index' %}">Homepage</a></li>
        <li><a href="{% url 'learning_logs:topics' %}">Topcis</a></li>
    </ul>
</nav>

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<header>
    {% include 'navbar.html' %}
</header>
<main>
    <h1>{{ topic }}</h1>
    {% for entry in entries %}
    <div>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </div>
    {% empty %}
    <div>
        <p>No entries have been added yet</p>
    </div>
    {% endfor %}
</main>
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<header>
</header>
<main>
    <ul>
        {% for topic in topics %}
            <li><a target="_blank" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
        {% empty %}
            <li>No topics have been added yet</li>
        {% endfor %}
    </ul>
</main>
{% endblock %}